# Generated by Django 3.2.7 on 2024-08-06 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='receive_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving', to='base.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='send_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sending', to='base.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sending', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='booking_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.bookingsession'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='state',
            field=models.CharField(blank=True, choices=[('AV', 'Available'), ('UP', 'Up Coming'), ('DR', 'During Training'), ('FN', 'Finished')], default='AV', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.svg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not specify')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='isTrainer',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
