# Generated by Django 3.2.7 on 2024-08-06 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20240806_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.course'),
        ),
    ]
