# Generated by Django 3.2.7 on 2024-11-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_userdevice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdevice',
            unique_together={('refresh_token', 'device_id')},
        ),
    ]
