# Generated by Django 3.2.7 on 2024-11-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_userdevice_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sport',
            field=models.CharField(choices=[('BM', 'Badminton'), ('BK', 'Basketball'), ('BX', 'Boxing'), ('FB', 'Football'), ('GY', 'Gym'), ('KB', 'Kickboxing'), ('SW', 'Swimming'), ('TN', 'Tennis'), ('VB', 'Voleyball'), ('YG', 'Yoga'), ('WL', 'Weight Lifting')], max_length=2),
        ),
    ]
