# Generated by Django 3.2.7 on 2024-11-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_course_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='min_trainee',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='star',
            field=models.FloatField(default=3.0),
        ),
        migrations.AlterField(
            model_name='course',
            name='sport',
            field=models.CharField(choices=[('BM', 'Badminton'), ('BK', 'Basketball'), ('BX', 'Boxing'), ('FB', 'Football'), ('GY', 'Gym'), ('KB', 'Kickboxing'), ('SW', 'Swimming'), ('TN', 'Tennis'), ('VB', 'Voleyball'), ('YG', 'Yoga')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(choices=[('BM', 'Badminton'), ('BK', 'Basketball'), ('BX', 'Boxing'), ('FB', 'Football'), ('GY', 'Gym'), ('KB', 'Kickboxing'), ('SW', 'Swimming'), ('TN', 'Tennis'), ('VB', 'Voleyball'), ('YG', 'Yoga')], max_length=20, unique=True),
        ),
    ]
