# Generated by Django 3.2.7 on 2024-11-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20241118_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.TextField(blank=True, default='Your location'),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_trainee',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='min_trainee',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='star',
            field=models.FloatField(blank=True, default=3.0),
        ),
    ]
