# Generated by Django 3.2.7 on 2024-12-05 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20241119_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='state',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('ON', 'Online'), ('OF', 'Offline')], max_length=2)),
                ('value', models.IntegerField()),
                ('payment_info', models.CharField(blank=True, max_length=1000)),
                ('momo_transaction_id', models.CharField(blank=True, max_length=100)),
                ('is_paid', models.BooleanField(blank=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sending', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='payment_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.payment'),
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
