# Generated by Django 3.2.7 on 2024-12-10 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20241206_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='course',
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='base.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='message',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='payment',
            name='momo_payment_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='success',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='training_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='booking_sessions', to='base.trainingsession'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('ONL', 'Online'), ('OFF', 'Offline')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to='base.course'),
        ),
    ]
