# Generated by Django 3.2.7 on 2024-12-10 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20241210_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsession',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.course'),
        ),
    ]
