# Generated by Django 3.2.7 on 2024-12-10 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_bookingsession_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsession',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.course'),
        ),
    ]
