# Generated by Django 3.2.7 on 2024-12-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_bookingsession_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsession',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.course'),
        ),
    ]
