# Generated by Django 5.1.4 on 2025-01-05 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_user_avatar_alter_user_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sports',
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_sessions', to='base.payment'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sport',
            field=models.CharField(choices=[('BM', 'Badminton'), ('BK', 'Basketball'), ('BX', 'Boxing'), ('FB', 'Football'), ('GY', 'Gym'), ('KB', 'Kickboxing'), ('SW', 'Swimming'), ('TN', 'Tennis'), ('VB', 'Voleyball'), ('YG', 'Yoga'), ('PB', 'Pickleball')], max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
