# Generated by Django 5.1.4 on 2025-01-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_course_location_remove_location_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
